"""add iban

Revision ID: 33731e6e5112
Revises: c0d2b5d8afb2
Create Date: 2022-07-24 11:25:20.711222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33731e6e5112'
down_revision = 'c0d2b5d8afb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrator', sa.Column('iban', sa.String(length=22), nullable=False))
    op.add_column('approver', sa.Column('iban', sa.String(length=22), nullable=False))
    op.add_column('complainer', sa.Column('iban', sa.String(length=22), nullable=False))
    op.alter_column('complaints', 'complainer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'complainer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('complainer', 'iban')
    op.drop_column('approver', 'iban')
    op.drop_column('administrator', 'iban')
    # ### end Alembic commands ###
